以下の追加を行います
ca-risken/diagnosis pull request #138
Opened 2022-03-31 07:01 UTC by iiiidaaa

- プラグインの脆弱性情報のFInding追加
- VulnDB APIの残り回数出力

2022-04-05 10:32 UTC, gassara-kys commented on cmd/wpscan/wpscan.go
> +		appLogger.Notifyf(logging.InfoLevel, "Remaining requests of VulnAPI is %v", wpscanResult.VulnAPI.RequestRemaining)
スキャンのたびに通知をするとすごい量の通知が来てしまうので、しきい値を設けて、それを下回るようならNotifyf、まだ余裕があるならInfofにしておきたいですね

2022-04-05 10:32 UTC, gassara-kys commented on cmd/wpscan/finding.go
> +	r := makeRecommend(message.ProjectID, 0, findingInf.RecommendType, findingInf.Risk, findingInf.Recommendation)
typePlugin  の場合はRecommend情報がnilになりそうですが、RecommendTypeデータが生成されてしまい結果的にPutRecommendで失敗しそうです。

2022-04-05 10:32 UTC, gassara-kys commented on cmd/wpscan/finding.go
> +func getPluginFinding(plugin plugin, message *message.WpscanQueueMessage) (*finding.FindingForUpsert, *finding.PutRecommendRequest, error) {
これは一つ意見ですが、この関数の戻り値が２つの構造体を返す形になっていて、一つの関数内の処理が複雑になっていそうです。この影響でコードやテストの見通しが悪くなってしまってるように感じます。もし業務ロジック的に分けることが可能なら
getPluginFinding と getPluginRecommend のように目的ごとに関数を分けると少しスッキリするかもしれません。

また、ここで返すFindingやRecommend情報を後続の処理でかなり持ち回しているので
pluginという構造体のメンバー変数にFinding、Recommendを保持するというような形にするとスッキリしそうです。 その場合は `json` タグをつけなければ、json.Marshalしたときに出力されない

2022-04-06 06:27 UTC, mmmknt commented on cmd/wpscan/finding.go
> +		return nil, nil, nil
プラグインの情報に紐づくfindingのデータが取得できなかった場合はエラーにしなくて良いのでしょうか？

2022-04-06 06:30 UTC, iiiidaaa commented on cmd/wpscan/wpscan.go
> +		appLogger.Notifyf(logging.InfoLevel, "Remaining requests of VulnAPI is %v", wpscanResult.VulnAPI.RequestRemaining)
おっしゃる通りです
一律Infofに修正して、閾値との比較・通知はカスタムメトリクスで実施しようと思います。

2022-04-06 06:32 UTC, iiiidaaa commented on cmd/wpscan/finding.go
> +func getPluginFinding(plugin plugin, message *message.WpscanQueueMessage) (*finding.FindingForUpsert, *finding.PutRecommendRequest, error) {
ありがとうございます！
可読性、処理の複雑さを考えてリファクタしたいと思います。
ただし、影響範囲が大きくなるため全体見直しを含めて別のPRでやらせていただければと思います。
いかがでしょうか。

2022-04-06 07:16 UTC, iiiidaaa commented on cmd/wpscan/finding.go
> +		return nil, nil, nil
途中で問題が発生してもFindingを登録し切るという意図で既存の類似箇所と同様にwarnにして、次を登録するように設定していました。
エラーに変更します。(類似箇所は@gassara-kysの指摘と同様別PRでやらせてください)

2022-04-06 10:54 UTC, iiiidaaa commented on cmd/wpscan/finding.go
> +	r := makeRecommend(message.ProjectID, 0, findingInf.RecommendType, findingInf.Risk, findingInf.Recommendation)
typePluginの場合、findingInf変数にRisk,Recommendationが空文字になるため[L205-207](https://github.com/ca-risken/diagnosis/blob/6a09fd7c888188bb91812a11a67d055df7e2d286/cmd/wpscan/finding.go#L205)にてnil値の*finding.PutRecommendRequestを返却します
そのため、[PutFindingのL241](https://github.com/ca-risken/diagnosis/blob/6a09fd7c888188bb91812a11a67d055df7e2d286/cmd/wpscan/finding.go#L241)のnilチェックにひっかかりRecommendを登録しない動きになっています。
recommendがnilの場合にputFindingからputRecommendを実行しないことを保証するためにテストを追加しました。

2022-04-06 12:05 UTC, mmmknt requested changes

2022-04-06 12:05 UTC, mmmknt commented on cmd/wpscan/finding.go
> +		return nil, nil, err
`err` は `data, err := json.Marshal(plugin)` でバインドされた値なので `nil` になっています。
ここでは処理の内容に紐づいたエラーを生成して返す必要があります。

2022-04-06 12:06 UTC, mmmknt commented on cmd/wpscan/finding.go
> +		return nil, nil, nil
方針はLGTMです！実装は修正が必要になりそうなので、追加のコメントを確認してもらえればと。

2022-04-06 13:26 UTC, gassara-kys commented on cmd/wpscan/finding.go
> +func getPluginFinding(plugin plugin, message *message.WpscanQueueMessage) (*finding.FindingForUpsert, *finding.PutRecommendRequest, error) {
承知しました！

2022-04-06 13:26 UTC, gassara-kys commented on cmd/wpscan/finding.go
> +	r := makeRecommend(message.ProjectID, 0, findingInf.RecommendType, findingInf.Risk, findingInf.Recommendation)
すいません、見間違えていました。Recommendがnilになるのならエラーにならなそうなので大丈夫かと思います。

2022-04-06 13:26 UTC, gassara-kys commented on cmd/wpscan/wpscan.go
> +	}
RequestRemaining の値でメトリクスを取るなら、↓のような構造化されたログを出力した方がベターです。
```go
remain := map[string]interface{}{
	"api_remaining": wpscanResult.VulnAPI.RequestRemaining,
}
appLogger.WithItems(logging.InfoLevel, remain, "Executed WPScan VulnAPI")
```

上記のようなログ出力するとapi_remaining というキーで数値を扱えるようになるので、後続の判定処理が少し楽になります。（すべて文字列で出力してしまうとパースの処理を入れる必要が出てくるため）

2022-04-06 13:27 UTC, gassara-kys commented on cmd/wpscan/wpscan.go
> +		appLogger.Notifyf(logging.InfoLevel, "Remaining requests of VulnAPI is %v", wpscanResult.VulnAPI.RequestRemaining)
承知しました！

2022-04-06 13:40 UTC, gassara-kys commented on cmd/wpscan/finding_test.go
> +}
`github.com/ca-risken/core/proto/finding/mocks` パッケージを使うとMockを自分で作らずにInterfaceから自動生成されたmockを利用することができます。なので mockFindingClient部分ごっそり削れます
参考として↓（ただ、ちょっと書き方が若干変わるのですが、、、、）
https://github.com/ca-risken/common/blob/master/pkg/sqs/finalizer_test.go

2022-04-07 03:16 UTC, iiiidaaa commented on cmd/wpscan/finding.go
> +		return nil, nil, err
ありがとうございます。fmt.Errorfでエラーを生成するようにしました。

2022-04-07 03:16 UTC, iiiidaaa commented on cmd/wpscan/wpscan.go
> +	}
いただいた内容に修正しました。

2022-04-07 03:52 UTC, iiiidaaa commented on cmd/wpscan/finding_test.go
> +}
github.com/ca-risken/core/proto/finding/mocks を使うように修正しました！

2022-04-07 05:38 UTC, gassara-kys approved these changes
LGTM

2022-04-07 05:44 UTC, mmmknt approved these changes
👍

2022-04-08 04:04 UTC, merged